[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
box_minter = "Hr39xMTdeQFPkLb9D6yYxxzTTkfW6QgVyyUETT7jyfZw"

[programs.localnet]
box_minter = "FPAzYdh8rdSRSXYQBneqwniqWGn3out5eQg2n1qyotxd"

[programs.mainnet]
box_minter = "7FGMn1z6TMi6ndyVooP9n1y3zuWhcrxfcJgcSQs6VNNU"

[programs.testnet]
box_minter = "22NeePs5wgkzP4j5sPzfzJqXsFAu9SUMiGBznPQVaAep"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
