export const MPL_CORE_PROGRAM_ADDRESS =
  'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d';
export const MPL_NOOP_PROGRAM_ADDRESS =
  'mnoopTCrg4p8ry25e4bcWA9XZjbNjMTfgYVGGEdRsf3';
export const SPL_NOOP_PROGRAM_ADDRESS =
  'noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV';
export const MPL_ACCOUNT_COMPRESSION_PROGRAM_ADDRESS =
  'mcmt6YrQEMKw8Mw43FmpRLmf7BqRnFMKmAcbxE3xkAW';
export const BUBBLEGUM_PROGRAM_ADDRESS =
  'BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY';
export const MPL_CORE_CPI_SIGNER_ADDRESS =
  'CbNY3JiXdXNE9tPNEk1aRZVEkWdj2v7kfJLNQwZZgpXk';
